#!/usr/bin/env node

'use strict'

const jsonFuture = require('json-future')
const getStdin = require('get-stdin')
const { concat } = require('lodash')
const cheerio = require('cheerio')

const REGEX_SEPARATOR = new RegExp('<br>', 'g')

const save = body => {
  return new Promise ((resolve, reject) => {
    const $ = cheerio.load(body)
    let result = []

    $('span > p').each(function (i, el) {
        if (i !== 0) {
          const domains = $(this).html().replace(REGEX_SEPARATOR, ' ').split(' ')
          result = concat(result, domains)
        }
    })
    jsonFuture.saveAsync('domains.json', result).then(resolve).catch(reject)
  })
}

getStdin().then(save).catch(err => {
  console.log('ERR!', err)
  process.exit(1)
})
