#!/usr/bin/env node

'use strict'

const jsonFuture = require('json-future')
const { concat } = require('lodash')
const cheerio = require('cheerio')

const {stdin} = process;

const getStdin = () => {
    return new Promise((resolve, reject) => {
        let result = '';

        if (stdin.isTTY) {
            return result;
        }
    
        stdin.setEncoding('utf8');
    
        for (const chunk of stdin) {
            result += chunk;
        }
    
        resolve(result)
    })
};

const REGEX_SEPARATOR = new RegExp('<br>', 'g')

const save = body => {
  return new Promise ((resolve, reject) => {
    const $ = cheerio.load(body)
    let result = []

    $('span > p').each(function (i, el) {
        if (i !== 0) {
          const domains = $(this).html().replace(REGEX_SEPARATOR, ' ').split(' ')
          result = concat(result, domains)
        }
    })
    jsonFuture.saveAsync('domains.json', result).then(resolve).catch(reject)
  })
}

getStdin().then(save).catch(err => {
  console.log('ERR!', err)
  process.exit(1)
})
